name: sympli_ai_health
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

  cupertino_icons: ^1.0.8

  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.1
  google_sign_in: ^6.2.1
  

  image_picker: ^1.0.7

  liquid_glass_renderer: ^0.1.1-dev.10

  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1

  flutter_native_splash: ^2.4.6

  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

  url_launcher: ^6.3.2

  http: ^1.5.0

  flutter_dotenv: ^5.2.1
  intl: ^0.20.2

  lottie: ^3.1.2
  audioplayers: ^6.1.0

  vibration: ^3.1.4

  android_intent_plus: ^5.0.2

  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2

  animate_do: ^3.1.2

  flutter_sound: ^9.2.13
  path_provider: ^2.1.2
  googleapis_auth: ^1.6.0
  permission_handler: ^12.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3

  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/sympli_logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/sympli_logo.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sympli_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/Sympli_Single_logo.png"